apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/base/frpc
  - ../../apps/base/frontend
  - ../../apps/base/backend
  - kustomizations/infrastructure-controllers.yaml
  - kustomizations/infrastructure-config.yaml
  - kustomizations/ecommerce-cs-agent-dev.yaml
  - kustomizations/fcihome-customer-chat.yaml

configMapGenerator:
  - name: fhg-frontend-values
    namespace: web
    files:
      - values.yaml=../../apps/overlays/dev/frontend-values.yaml
    options:
      disableNameSuffixHash: true
  - name: fhg-backend-values
    namespace: api
    files:
      - values.yaml=../../apps/overlays/dev/backend-values.yaml
    options:
      disableNameSuffixHash: true
