apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: ecommerce-minio
    app.kubernetes.io/component: object-storage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ecommerce-minio
    app.kubernetes.io/component: object-storage
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console

