apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=flux
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: HTTP_PROXY
        value: http://192.168.1.198:1087
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: HTTPS_PROXY
        value: http://192.168.1.198:1087
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: NO_PROXY
        value: localhost,127.0.0.1,.svc,.svc.,.cluster.local,.cluster.local.,source-controller,source-controller.flux-system.svc,source-controller.flux-system.svc.cluster.local,source-controller.flux-system.svc.cluster.local.,notification-controller,notification-controller.flux-system.svc,notification-controller.flux-system.svc.cluster.local,notification-controller.flux-system.svc.cluster.local.,192.168.1.0/24,10.0.0.0/8,10.42.0.0/16,10.43.0.0/16
