apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - target:
      kind: Deployment
      name: source-controller
    patch: &fluxProxyPatch |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: HTTP_PROXY
          value: http://192.168.1.198:1087
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: HTTPS_PROXY
          value: http://192.168.1.198:1087
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NO_PROXY
          value: localhost,127.0.0.1,.svc,.cluster.local,10.42.0.0/16,10.43.0.0/16,192.168.0.0/16,172.16.0.0/12
  - target:
      kind: Deployment
      name: kustomize-controller
    patch: *fluxProxyPatch
  - target:
      kind: Deployment
      name: helm-controller
    patch: *fluxProxyPatch
  - target:
      kind: Deployment
      name: notification-controller
    patch: *fluxProxyPatch
