apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce-cs-agent-dev
resources:
  - namespace.yaml
  - ../../../base/ecommerce-cs-agent
  - app-source.yaml
  - app-release.yaml

configMapGenerator:
  - name: ecommerce-cs-agent-values
    files:
      - values.yaml=values.yaml
    options:
      disableNameSuffixHash: true

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: ecommerce-cs-agent
      app.kubernetes.io/managed-by: flux
